# Generated by Django 3.2.5 on 2021-11-30 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_following_like'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='following',
            unique_together={('follower', 'influencer')},
        ),
    ]
