# Generated by Django 3.2.5 on 2021-12-10 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20211208_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='like_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_post', to='network.post'),
        ),
    ]
